[build]
  command = "cd client && pnpm install && pnpm build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "https://infinite-clothing-backend-dwea.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd client && pnpm dev"
  port = 5173
  targetPort = 5173
  publish = "client/dist"

